// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
public class BaiTap1 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void bT1() {
        driver.get("https://demoqa.com/automation-practice-form");
        driver.manage().window().setSize(new Dimension(1440, 819));


//    driver.get("https://demoqa.com/automation-practice-form");
//    driver.manage().window().setSize(new Dimension(1440, 819));
        driver.findElement(By.id("firstName")).click();
        driver.findElement(By.id("firstName")).sendKeys("Nhung");
        driver.findElement(By.id("lastName")).click();
        driver.findElement(By.id("lastName")).sendKeys("Nguyen");
        driver.findElement(By.id("userEmail")).click();
        driver.findElement(By.id("userEmail")).sendKeys("nhung123@gmail.com");
        driver.findElement(By.id("userNumber")).click();
        driver.findElement(By.id("userNumber")).sendKeys("0929023169");
        driver.findElement(By.cssSelector(".custom-checkbox:nth-child(1) > .custom-control-label")).click();

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        WebElement element = wait.until(ExpectedConditions.elementToBeClickable(By.id("currentAddress")));
        element.click();
        driver.findElement(By.id("currentAddress")).click();
        driver.findElement(By.id("currentAddress")).sendKeys("123");
        driver.findElement(By.cssSelector(".css-1pahdxg-control > .css-1hwfws3")).click();
        driver.findElement(By.id("react-select-3-option-0")).click();
        driver.findElement(By.cssSelector(".css-1pahdxg-control .css-1wa3eu0-placeholder")).click();
        driver.findElement(By.id("react-select-4-option-0")).click();
        driver.findElement(By.id("submit")).click();
        driver.findElement(By.cssSelector(".custom-radio:nth-child(1) > .custom-control-label")).click();
        driver.findElement(By.id("submit")).click();
        {
            element = driver.findElement(By.id("submit"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("closeLargeModal")).click();
    }
}

